# Generated by Django 3.2.7 on 2021-10-19 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_todo_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='private',
            field=models.BooleanField(default=True),
        ),
    ]
